//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace CogentDemo.Code.DocumentTypes
{
	/// <summary>Banner</summary>
	[PublishedContentModel("bannerSection")]
	public partial class BannerSection : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "bannerSection";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public BannerSection(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<BannerSection, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Background
		///</summary>
		[ImplementPropertyType("Background")]
		public IPublishedContent Background
		{
			get { return this.GetPropertyValue<IPublishedContent>("Background"); }
		}

		///<summary>
		/// Call To Action Subtitle
		///</summary>
		[ImplementPropertyType("bannerSubtitle")]
		public string BannerSubtitle
		{
			get { return this.GetPropertyValue<string>("bannerSubtitle"); }
		}

		///<summary>
		/// Call to Action Title
		///</summary>
		[ImplementPropertyType("bannerTitle")]
		public string BannerTitle
		{
			get { return this.GetPropertyValue<string>("bannerTitle"); }
		}

		///<summary>
		/// Call To Action Link
		///</summary>
		[ImplementPropertyType("primaryLink")]
		public Umbraco.Web.Models.Link PrimaryLink
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.Link>("primaryLink"); }
		}

		///<summary>
		/// Call To Action Link Text
		///</summary>
		[ImplementPropertyType("primaryLinkText")]
		public string PrimaryLinkText
		{
			get { return this.GetPropertyValue<string>("primaryLinkText"); }
		}
	}
}
