//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace CogentDemo.Code.DocumentTypes
{
	/// <summary>Call To Action</summary>
	[PublishedContentModel("callToActionSection")]
	public partial class CallToActionSection : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "callToActionSection";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public CallToActionSection(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<CallToActionSection, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Content
		///</summary>
		[ImplementPropertyType("callContent")]
		public IHtmlString CallContent
		{
			get { return this.GetPropertyValue<IHtmlString>("callContent"); }
		}

		///<summary>
		/// Link
		///</summary>
		[ImplementPropertyType("callLink")]
		public Umbraco.Web.Models.Link CallLink
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.Link>("callLink"); }
		}

		///<summary>
		/// Link Text
		///</summary>
		[ImplementPropertyType("callTitle")]
		public string CallTitle
		{
			get { return this.GetPropertyValue<string>("callTitle"); }
		}
	}
}
