//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace CogentDemo.Code.DocumentTypes
{
	// Mixin content Type 1172 with alias "CopyPart"
	/// <summary>Copy Part</summary>
	public partial interface ICopyPart : IPublishedContent
	{
		/// <summary>Text</summary>
		IHtmlString Text { get; }
	}

	/// <summary>Copy Part</summary>
	[PublishedContentModel("CopyPart")]
	public partial class CopyPart : PublishedContentModel, ICopyPart
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "CopyPart";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public CopyPart(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<CopyPart, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Text
		///</summary>
		[ImplementPropertyType("text")]
		public IHtmlString Text
		{
			get { return GetText(this); }
		}

		/// <summary>Static getter for Text</summary>
		public static IHtmlString GetText(ICopyPart that) { return that.GetPropertyValue<IHtmlString>("text"); }
	}
}
