//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace CogentDemo.Code.DocumentTypes
{
	// Mixin content Type 1329 with alias "headerSection"
	/// <summary>Spotlight Section</summary>
	public partial interface IHeaderSection : IPublishedContent
	{
		/// <summary>Image</summary>
		IPublishedContent HeaderImage { get; }

		/// <summary>Snippet</summary>
		string HeaderSubtitle { get; }

		/// <summary>Title</summary>
		string HeaderTitle { get; }
	}

	/// <summary>Spotlight Section</summary>
	[PublishedContentModel("headerSection")]
	public partial class HeaderSection : PublishedContentModel, IHeaderSection
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "headerSection";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HeaderSection(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HeaderSection, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Image: Add an image to be used in the SPotlight for your article
		///</summary>
		[ImplementPropertyType("headerImage")]
		public IPublishedContent HeaderImage
		{
			get { return GetHeaderImage(this); }
		}

		/// <summary>Static getter for Image</summary>
		public static IPublishedContent GetHeaderImage(IHeaderSection that) { return that.GetPropertyValue<IPublishedContent>("headerImage"); }

		///<summary>
		/// Snippet: Provide a brief summary of the article
		///</summary>
		[ImplementPropertyType("headerSubtitle")]
		public string HeaderSubtitle
		{
			get { return GetHeaderSubtitle(this); }
		}

		/// <summary>Static getter for Snippet</summary>
		public static string GetHeaderSubtitle(IHeaderSection that) { return that.GetPropertyValue<string>("headerSubtitle"); }

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("headerTitle")]
		public string HeaderTitle
		{
			get { return GetHeaderTitle(this); }
		}

		/// <summary>Static getter for Title</summary>
		public static string GetHeaderTitle(IHeaderSection that) { return that.GetPropertyValue<string>("headerTitle"); }
	}
}
