//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace CogentDemo.Code.DocumentTypes
{
	/// <summary>Image</summary>
	[PublishedContentModel("imageSection")]
	public partial class ImageSection : PublishedContentModel, IImageComposition
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "imageSection";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ImageSection(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ImageSection, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Image
		///</summary>
		[ImplementPropertyType("image")]
		public IPublishedContent Image
		{
			get { return CogentDemo.Code.DocumentTypes.ImageComposition.GetImage(this); }
		}

		///<summary>
		/// Image Alignment
		///</summary>
		[ImplementPropertyType("imageAlignment")]
		public string ImageAlignment
		{
			get { return CogentDemo.Code.DocumentTypes.ImageComposition.GetImageAlignment(this); }
		}

		///<summary>
		/// Link
		///</summary>
		[ImplementPropertyType("link")]
		public Umbraco.Web.Models.Link Link
		{
			get { return CogentDemo.Code.DocumentTypes.ImageComposition.GetLink(this); }
		}
	}
}
