//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace CogentDemo.Code.DocumentTypes
{
	// Mixin content Type 1300 with alias "imageComposition"
	/// <summary>Image Composition</summary>
	public partial interface IImageComposition : IPublishedContent
	{
		/// <summary>Image</summary>
		IPublishedContent Image { get; }

		/// <summary>Image Alignment</summary>
		string ImageAlignment { get; }

		/// <summary>Link</summary>
		Umbraco.Web.Models.Link Link { get; }
	}

	/// <summary>Image Composition</summary>
	[PublishedContentModel("imageComposition")]
	public partial class ImageComposition : PublishedContentModel, IImageComposition
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "imageComposition";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ImageComposition(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ImageComposition, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Image
		///</summary>
		[ImplementPropertyType("image")]
		public IPublishedContent Image
		{
			get { return GetImage(this); }
		}

		/// <summary>Static getter for Image</summary>
		public static IPublishedContent GetImage(IImageComposition that) { return that.GetPropertyValue<IPublishedContent>("image"); }

		///<summary>
		/// Image Alignment
		///</summary>
		[ImplementPropertyType("imageAlignment")]
		public string ImageAlignment
		{
			get { return GetImageAlignment(this); }
		}

		/// <summary>Static getter for Image Alignment</summary>
		public static string GetImageAlignment(IImageComposition that) { return that.GetPropertyValue<string>("imageAlignment"); }

		///<summary>
		/// Link
		///</summary>
		[ImplementPropertyType("link")]
		public Umbraco.Web.Models.Link Link
		{
			get { return GetLink(this); }
		}

		/// <summary>Static getter for Link</summary>
		public static Umbraco.Web.Models.Link GetLink(IImageComposition that) { return that.GetPropertyValue<Umbraco.Web.Models.Link>("link"); }
	}
}
