//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace CogentDemo.Code.DocumentTypes
{
	// Mixin content Type 1163 with alias "linkPart"
	/// <summary>Link Part</summary>
	public partial interface ILinkPart : IPublishedContent
	{
		/// <summary>Link</summary>
		Umbraco.Web.Models.Link Link { get; }
	}

	/// <summary>Link Part</summary>
	[PublishedContentModel("linkPart")]
	public partial class LinkPart : PublishedContentModel, ILinkPart
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "linkPart";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public LinkPart(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<LinkPart, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Link
		///</summary>
		[ImplementPropertyType("link")]
		public Umbraco.Web.Models.Link Link
		{
			get { return GetLink(this); }
		}

		/// <summary>Static getter for Link</summary>
		public static Umbraco.Web.Models.Link GetLink(ILinkPart that) { return that.GetPropertyValue<Umbraco.Web.Models.Link>("link"); }
	}
}
