//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace CogentDemo.Code.DocumentTypes
{
	// Mixin content Type 1330 with alias "listingPageBase"
	/// <summary>Listing Page Base</summary>
	public partial interface IListingPageBase : IPublishedContent
	{
		/// <summary>Items Per Row</summary>
		object ItemsPerRow { get; }
	}

	/// <summary>Listing Page Base</summary>
	[PublishedContentModel("listingPageBase")]
	public partial class ListingPageBase : PublishedContentModel, IListingPageBase
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "listingPageBase";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ListingPageBase(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ListingPageBase, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Items Per Row
		///</summary>
		[ImplementPropertyType("itemsPerRow")]
		public object ItemsPerRow
		{
			get { return GetItemsPerRow(this); }
		}

		/// <summary>Static getter for Items Per Row</summary>
		public static object GetItemsPerRow(IListingPageBase that) { return that.GetPropertyValue("itemsPerRow"); }
	}
}
