//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace CogentDemo.Code.DocumentTypes
{
	/// <summary>Navigation</summary>
	[PublishedContentModel("nav")]
	public partial class Nav : PublishedContentModel, INavigation
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "nav";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Nav(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Nav, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Brand Link
		///</summary>
		[ImplementPropertyType("brandLink")]
		public Umbraco.Web.Models.Link BrandLink
		{
			get { return CogentDemo.Code.DocumentTypes.Navigation.GetBrandLink(this); }
		}

		///<summary>
		/// Brand Logo
		///</summary>
		[ImplementPropertyType("brandLogo")]
		public IPublishedContent BrandLogo
		{
			get { return CogentDemo.Code.DocumentTypes.Navigation.GetBrandLogo(this); }
		}

		///<summary>
		/// Main Navigation
		///</summary>
		[ImplementPropertyType("mainNavigation")]
		public IEnumerable<Umbraco.Web.Models.Link> MainNavigation
		{
			get { return CogentDemo.Code.DocumentTypes.Navigation.GetMainNavigation(this); }
		}

		///<summary>
		/// siteTitle
		///</summary>
		[ImplementPropertyType("siteTitle")]
		public string SiteTitle
		{
			get { return CogentDemo.Code.DocumentTypes.Navigation.GetSiteTitle(this); }
		}
	}
}
